# Generated by Django 3.2.19 on 2023-08-23 18:58

from django.db import migrations, models
import django.db.models.deletion
import test_projects.test_proj.test_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOTokenTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=80)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens_two', to='test_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='SSOToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_column='token', max_length=80)),
                ('expires', models.DateTimeField(db_column='expires', default=test_projects.test_proj.test_app.models.get_token_expiration)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens', to='test_app.user')),
            ],
        ),
    ]
