# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER=test

    working_directory: ~/drfsig

    steps:
      - checkout

      # need to install pyodbc dependency
      - run:
          name: pyodbc dependency
          command: |
            sudo apt-get install unixodbc unixodbc-dev

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir xunit
            . venv/bin/activate
            cd test_projects/test_proj
            python manage.py test --with-xunit --xunit-file=../../xunit/xunit-test_proj.xml
            cd ../test_cognito_proj
            python manage.py test --with-xunit --xunit-file=../../xunit/xunit-cognito_test_proj.xml

      # store test results
      - store_test_results:
          path: ./xunit

      # store xml test artifacts
      - store_artifacts:
          path: ./xunit

      # deploy to pypi
      - deploy:
          name: PyPi Deploy
          # upgrade pip to successfully install cryptography package
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo pip install twine
              sudo pip install --upgrade pip
              python setup.py sdist
              twine upload --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" dist/*
            fi
