# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-24 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_signature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_key', models.CharField(max_length=32)),
                ('request_value', models.CharField(max_length=32)),
                ('api_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_signature.ApiEndpoint')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_signature.ApiKey')),
            ],
        ),
    ]
