# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-10-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_signature', '0002_apirequestpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='bypass_user_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apikey',
            name='full_access',
            field=models.BooleanField(default=False),
        ),
    ]
